### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jasqs** [OpenGATE/gam-gate#42]
The installation of the gam-gate went correctly but when importing the module in python I am getting an error.

`Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
> import gam_gate as gam
gam-g4 is not detected. Be sure to execute these lines before to run python:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\~/.local/lib/python3.9/site-packages/gam_gate/\_\_init\_\_.py", line 8, in <module>
    from .geometry.VolumeManager import \_\_world_name\_\_
  File "\~/.local/lib/python3.9/site-packages/gam_gate/geometry/VolumeManager.py", line 3, in <module>
    import gam_g4 as g4
  File "\~/.local/lib/python3.9/site-packages/gam_g4/\_\_init\_\_.py", line 28, in <module>
    print("export LD_LIBRARY_PATH=" + os.path.join(get_site_packages_dir(), "gam_g4.libs") + ":${LD_LIBRARY_PATH}")
  File "\~/.local/lib/python3.9/site-packages/gam_g4/\_\_init\_\_.py", line 7, in get_site_packages_dir
    site_package = [p for p  in site.getsitepackages()
IndexError: list index out of range
`

**Comment by jasqs** [comment]
I have recognised the problem. 

**site.getsitepackages()** gets just the site packages installed globally. Additionally to this, a **site.getusersitepackages()** should be used to cover the cases when a user installs the package locally, i.e. by _pip install gam-gate_ instead of _sudo pip install gam-gate_

**Comment by tbaudier** [comment]
Hi @jasqs 

You're right, there is a problem with **site.getsitepackages()** but it works on our computers. The problematic lines are [here](https://github.com/OpenGATE/gam-gate/blob/master/gam_g4/gam_g4/__init__.py#L28). I investigate a little bit more.

To answer to your second problem, before to start python, you need to preload 2 librairies executing this line:
```
export LD_PRELOAD=/usr/local/lib/python3.9/dist-packages/gam_g4/../gam_g4.libs/libG4geometry-032f248e.so:/usr/local/lib/python3.9/dist-packages/gam_g4/../gam_g4.libs/libG4processes-XXXXX.so:${LD_PRELOAD}
```
replace the XXXX by the correct name

**Comment by dsarrut** [comment]
yes, the "preload" thing is really annoying.  It is set automatically for users when they `pip install`, but this is not the case for manual develop installation. This is not needed on osx.

**Comment by tbaudier** [comment]
I tried to debug the first issue with this PR https://github.com/OpenGATE/gam-gate/pull/43

Can you try it on your computer please because I cannot reproduce the error.

You can download the wheel here: https://github.com/OpenGATE/gam-gate/actions/runs/2513825090 (at the bottom click on the **dist** artifact) and install the wheels of gam_g4 and gam_gate corresponding to your python version and OS. Thank you very much

**Comment by jasqs** [comment]
> I tried to debug the first issue with this PR #43
> 
> Can you try it on your computer please because I cannot reproduce the error.
> 
> You can download the wheel here: https://github.com/OpenGATE/gam-gate/actions/runs/2513825090 (at the bottom click on the **dist** artifact) and install the wheels of gam_g4 and gam_gate corresponding to your python version and OS. Thank you very much

I have installed the gam_g4 and gam_gate, i.e. first 
> pip install gam_g4-0.4.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl 

and then

> pip install gam_gate-0.4.0-py3-none-any.whl

I seems to work properly now. I have exported all LD_PRELOAD and imported the gam_gate in python3.9. It downloaded all the g4 data properly.

**Comment by jasqs** [comment]
The gam_gate import in python3.9 works but not in jupyterlab (the same python verison). I am getting the same error as before, with allocating memory in static TLS block. 

![image](https://user-images.githubusercontent.com/7965093/174558408-f209b1fb-ff62-45ae-9db4-9a84339a74b7.png)

do you have any idea?

**Comment by tbaudier** [comment]
The LD_PRELOAD EXPORT should be set before the starting of python and/or jupyter. Maybe you can try to export it befor to run jupyter notebook in the terminal
